on:
  push:         # here to simplify using nektos/act
  issues:
    types: [opened, edited, milestoned]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: hub example
      shell: bash
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        cat templates/head.tmpl > index.html
        echo "<body>" >>index.html
        echo "<h1>Could this be enough?</h1>" >>index.html
        bin/hub issue --format "<span><h2><a href='%U'>%t</a> %cr</h2><div>%b</div></span>%n" >>index.html
        echo "/<body>" >>index.html
        echo "/<html>" >>index.html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Update index.html
        branch: ${{ github.head_ref }}
